<a href="https://colab.research.google.com/github/fiedler-m/classifier_app/blob/main/KNN_Image_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
import pandas as pd

from sklearn import preprocessing
from sklearn.model_selection import train_test_split

from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import jaccard_similarity_score, f1_score, log_loss

import seaborn as sns

import matplotlib.pyplot as plt
%matplotlib inline


In [23]:
url = 'https://github.com/fiedler-m/classifier_app/raw/main/iris_data.csv'

iris_df = pd.read_csv(url)

In [73]:
iris_df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [74]:
X = iris_df[['sepal.length', 'sepal.width', 'petal.length', 'petal.width']].values
X[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [75]:
y = iris_df['variety'].values

In [76]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state =3)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (105, 4) (105,)
Test set: (45, 4) (45,)


In [77]:
X_train = preprocessing.StandardScaler().fit(X_train).transform(X_train.astype(float))
X_train[0:5]

array([[ 0.68955032,  0.29978535,  0.38919985,  0.37287433],
       [-0.96174124,  0.536458  , -1.22696903, -0.9588197 ],
       [ 0.18146061, -0.88357788,  0.73552176,  0.50604373],
       [-0.07258424, -0.88357788,  0.73552176,  0.90555194],
       [-0.58067396, -0.17355994,  0.38919985,  0.37287433]])

In [78]:
X_test = preprocessing.StandardScaler().fit(X_test).transform(X_test.astype(float))
X_test[0:5]

array([[-1.33519891,  0.39233578, -1.21491142, -1.22307682],
       [-1.33519891,  0.17437146, -1.15968817, -1.22307682],
       [-0.45323266,  0.82826443, -1.15968817, -0.96588777],
       [-0.89421579, -0.04359286, -1.10446493, -1.22307682],
       [-0.12249531,  3.00790765, -1.15968817, -0.96588777]])

In [79]:
model = KNeighborsClassifier(n_neighbors = 3)
model.fit(X_train,y_train)
prediction = model.predict(X_test)

print("Accuracy of the KNN model: ", accuracy_score(y_test, yhat_KNN))

Accuracy of the KNN model:  0.9111111111111111
